"use client";

import { useEffect, useRef, useState } from "react";
import { NoraResult, Persona } from "@/lib/types";

interface PrivacyReceiptProps {
  result: NoraResult;
  persona: Persona;
  originalMessage: string;
  timestamp: string;
}

function ScoreCircle({ score }: { score: number }) {
  const radius = 40;
  const circumference = 2 * Math.PI * radius;
  const [offset, setOffset] = useState(circumference);

  const strokeColor =
    score >= 70 ? "#22c55e" : score >= 40 ? "#eab308" : "#ef4444";

  useEffect(() => {
    const t = setTimeout(() => {
      setOffset(circumference - (score / 100) * circumference);
    }, 200);
    return () => clearTimeout(t);
  }, [score, circumference]);

  return (
    <div className="relative flex items-center justify-center w-24 h-24">
      <svg className="absolute inset-0 w-full h-full -rotate-90" viewBox="0 0 100 100">
        <circle cx="50" cy="50" r={radius} fill="none" stroke="#2a2a2a" strokeWidth="8" />
        <circle
          cx="50"
          cy="50"
          r={radius}
          fill="none"
          stroke={strokeColor}
          strokeWidth="8"
          strokeLinecap="round"
          style={{
            strokeDasharray: circumference,
            strokeDashoffset: offset,
            transition: "stroke-dashoffset 1.2s ease-in-out",
          }}
        />
      </svg>
      <div className="relative text-center">
        <span className="text-2xl font-bold" style={{ color: strokeColor }}>
          {score}
        </span>
        <span className="block text-xs text-gray-500 leading-none">%</span>
      </div>
    </div>
  );
}

export default function PrivacyReceipt({ result, persona, originalMessage, timestamp }: PrivacyReceiptProps) {
  const receiptRef = useRef<HTMLDivElement>(null);
  const [copied, setCopied] = useState(false);

  const high = result.sensitive_detected.filter((d) => d.risk === "high");
  const medium = result.sensitive_detected.filter((d) => d.risk === "medium");
  const low = result.sensitive_detected.filter((d) => d.risk === "low");

  function handleDownload() {
    const lines = [
      "╔════════════════════════════════════════╗",
      "║         NORA PRIVACY RECEIPT           ║",
      "╚════════════════════════════════════════╝",
      "",
      `Timestamp  : ${timestamp}`,
      `Persona    : ${persona.toUpperCase()}`,
      "",
      "── SIGNALS DETECTED ──────────────────────",
      ...result.sensitive_detected.map(
        (d) => `  [${d.risk.toUpperCase()}] ${d.type}: "${d.text}"`
      ),
      "",
      "── DATA REMOVED ──────────────────────────",
      ...result.sensitive_detected.map((d) => `  - ${d.type}`),
      "",
      "── DATA SENT TO AI ───────────────────────",
      `  "${result.rewritten_message}"`,
      "",
      `── PROTECTION SCORE: ${result.protection_score}% ─────────────`,
      "",
      result.persona_impact,
      "",
      "Generated by Nora Privacy Governance",
    ];
    const text = lines.join("\n");
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return (
    <div>
      <div className="flex items-center gap-2 mb-3">
        <span className="text-xs font-semibold text-gray-400 uppercase tracking-widest">
          Privacy Receipt
        </span>
        <span className="text-xs text-gray-600">— audit log of this session</span>
      </div>

      <div
        ref={receiptRef}
        className="rounded-lg border border-[#2a2a2a] bg-[#1a1a1a] overflow-hidden"
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-[#2a2a2a] bg-[#141414]">
          <div>
            <div className="flex items-center gap-2">
              <svg className="h-4 w-4 text-purple-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
              </svg>
              <span className="font-semibold text-gray-200">Nora Privacy Audit</span>
            </div>
            <p className="text-xs text-gray-600 mt-1 font-mono">{timestamp}</p>
          </div>
          <ScoreCircle score={result.protection_score} />
        </div>

        {/* Content grid */}
        <div className="p-5 grid grid-cols-1 md:grid-cols-2 gap-5">
          {/* Left column */}
          <div className="space-y-4">
            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wider mb-1.5">Persona Used</p>
              <span
                className={`inline-block text-sm font-semibold px-3 py-1 rounded-full capitalize
                  ${persona === "conservative" ? "bg-purple-900/40 text-purple-300 border border-purple-800" :
                    persona === "balanced" ? "bg-blue-900/40 text-blue-300 border border-blue-800" :
                    "bg-green-900/40 text-green-300 border border-green-800"}`}
              >
                {persona}
              </span>
            </div>

            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wider mb-1.5">Signals Detected</p>
              <div className="flex gap-3">
                {high.length > 0 && (
                  <div className="text-center">
                    <p className="text-lg font-bold text-red-400">{high.length}</p>
                    <p className="text-xs text-gray-600">High</p>
                  </div>
                )}
                {medium.length > 0 && (
                  <div className="text-center">
                    <p className="text-lg font-bold text-orange-400">{medium.length}</p>
                    <p className="text-xs text-gray-600">Medium</p>
                  </div>
                )}
                {low.length > 0 && (
                  <div className="text-center">
                    <p className="text-lg font-bold text-yellow-400">{low.length}</p>
                    <p className="text-xs text-gray-600">Low</p>
                  </div>
                )}
                {result.sensitive_detected.length === 0 && (
                  <p className="text-sm text-gray-600 italic">None</p>
                )}
              </div>
            </div>

            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wider mb-1.5">Data Removed</p>
              {result.sensitive_detected.length === 0 ? (
                <p className="text-sm text-gray-600 italic">Nothing removed</p>
              ) : (
                <div className="flex flex-col gap-1">
                  {result.sensitive_detected.map((item, i) => (
                    <p key={i} className="text-xs text-gray-400 font-mono">
                      — <span className="text-gray-500">{item.type}:</span> "{item.text.length > 30 ? item.text.slice(0, 30) + "…" : item.text}"
                    </p>
                  ))}
                </div>
              )}
            </div>
          </div>

          {/* Right column */}
          <div className="space-y-4">
            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wider mb-1.5">Data Sent to AI</p>
              <p className="text-sm text-gray-300 font-mono bg-[#111] rounded px-3 py-2 border border-[#2a2a2a] italic text-xs leading-relaxed">
                "{result.rewritten_message}"
              </p>
            </div>

            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wider mb-1.5">Persona Impact</p>
              <p className="text-sm text-gray-300">{result.persona_impact}</p>
            </div>

            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wider mb-1.5">Protection Score</p>
              <div className="flex items-center gap-3">
                <div
                  className={`text-3xl font-bold ${
                    result.protection_score >= 70 ? "text-green-400" :
                    result.protection_score >= 40 ? "text-yellow-400" : "text-red-400"
                  }`}
                >
                  {result.protection_score}%
                </div>
                <div className="text-xs text-gray-600">
                  {result.protection_score >= 70 ? "Strong protection" :
                   result.protection_score >= 40 ? "Moderate protection" : "Low protection"}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="px-5 py-3 border-t border-[#2a2a2a] bg-[#141414] flex items-center justify-between">
          <p className="text-xs text-gray-700">Generated by Nora Privacy Governance</p>
          <button
            onClick={handleDownload}
            className="flex items-center gap-1.5 text-xs text-purple-400 hover:text-purple-300 transition-colors px-3 py-1.5 rounded border border-purple-900/50 hover:bg-purple-900/20"
          >
            {copied ? (
              <>
                <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
                Copied!
              </>
            ) : (
              <>
                <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                </svg>
                Copy Receipt
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
